Repository LiveSplit/LiveSplitOne, pull requests merged in 2020-05, with the labels that each got.

#350 Make hotkey buttons not rely on focus and blur anymore
  src/css/HotkeyButton.scss
  src/ui/HotkeyButton.tsx
  test/rendering-test.js
Labels: Firefox, bug

#348 Fix empty columns affecting columns to the left
  src/layout/Split.tsx
Labels: bug, layout rendering

#347 Replace checkboxes with toggles
  package-lock.json
  package.json
  src/css/ColorPicker.scss
  src/css/RunEditor.scss
  src/css/Table.scss
  src/css/ToggleCheckbox.scss
  src/css/variables.scss
  src/ui/ColorPicker.tsx
  src/ui/HotkeyButton.tsx
  src/ui/RunEditor.tsx
  src/ui/Settings.tsx
  src/ui/ToggleCheckbox.tsx
Labels: UI, enhancement

#358 Resolve Keys based on the Keyboard Layout
  src/ui/HotkeyButton.tsx
Labels: UI, enhancement

#359 Fix hotkey buttons keeping the listener even after a blur
  src/ui/HotkeyButton.tsx
Labels: bug

#361 Fix toggles not properly updating when switching views
  src/ui/LayoutEditor.tsx
  src/ui/RunEditor.tsx
  src/ui/Settings.tsx
  src/ui/SettingsEditor.tsx
  src/ui/ToggleCheckbox.tsx
Labels: UI, bug

#365 Only re-render components when necessary
  package-lock.json
  package.json
  src/layout/Component.tsx
  src/layout/Layout.tsx
  src/layout/Separator.tsx
  src/layout/Split.tsx
  src/layout/Splits.tsx
Labels: enhancement, layout rendering, performance
