Repository LiveSplit/LiveSplitOne, pull requests merged in 2020-06, with the labels that each got.

#378 Improve Paint Times
  src/css/Timer.scss
  src/layout/Timer.tsx
Labels: enhancement, layout rendering, performance

#380 Add parent params to twitch embeds
  src/ui/Embed.tsx
Labels: UI, bug, speedrun.com integration

#382 Add a threshold for the image hash comparison
  package.json
  test/rendering-test.js
Labels: CI
