Repository LiveSplit/LiveSplitOne, pull requests merged in 2020-01, with the labels that each got.

#209 Make the initial loading indicator look better
  src/css/main.scss
  src/index.tsx
Labels: enhancement

#211 Remove Mention of Electron from README.md
  README.md
Labels: enhancement

#210 Update start:electron npm target
  package.json
Labels: enhancement

#214 Always show the sidebar when the screen is wide enough
  src/css/DragUpload.scss
  src/css/LayoutEditor.scss
  src/css/LiveSplit.scss
  src/css/RunEditor.scss
  src/css/SettingsEditor.scss
  src/ui/LayoutEditor.tsx
  src/ui/LiveSplit.tsx
  src/ui/RunEditor.tsx
Labels: CSS, enhancement

#220 Add Splits and Layout submenus to the sidebar
  src/assets/icon_small.png
  src/css/SideBarContent.scss
  src/type-definitions/images.d.ts
  src/ui/LiveSplit.tsx
  src/ui/SideBarContent.tsx
Labels: enhancement

#218 Hide Run Editor tabs when they are not applicable
  src/css/ContextMenu.scss
  src/css/DragUpload.scss
  src/css/LiveSplit.scss
  src/css/Markdown.scss
  src/css/RunEditor.scss
  src/css/SideBarContent.scss
  src/css/Table.scss
  src/css/Toggle.scss
  src/css/main.scss
  src/css/variables.scss
  src/ui/RunEditor.tsx
Labels: CSS, enhancement

#221 Switch to fontawesome 5 and change icons for Splits and Layout
  src/css/font-awesome.css
  src/css/fontawesome-webfont.woff
  src/ui/SideBarContent.tsx
Labels: CSS, enhancement

#222 Change colors to have more contrast
  src/css/variables.scss
Labels: CSS, enhancement

#223 Set up GitHub Actions
  .github/workflows/build.sh
  .github/workflows/ci.yml
  .github/workflows/install.sh
  .travis.yml
  README.md
  ci/deploy_key.enc
  ci/deploy_key.pub
  ci/install.sh
  ci/script.sh
Labels: enhancement

#224 Allow KeyValue and Text components to show two rows
  src/css/KeyValue.scss
  src/css/Text.scss
  src/css/variables.scss
  src/layout/DetailedTimer.tsx
  src/layout/KeyValue.tsx
  src/layout/KeyValueGeneric.tsx
  src/layout/Text.tsx
Labels: UI, enhancement

#229 Key the caches by the current two weeks
  .github/workflows/ci.yml
Labels: enhancement

#225 Show variable values as leaderboard columns
  src/css/LiveSplit.scss
  src/css/Markdown.scss
  src/css/RunEditor.scss
  src/ui/Embed.tsx
  src/ui/RunEditor.tsx
Labels: UI, enhancement, speedrun.com integration

#236 Add buttons to load the default splits and layout
  src/ui/LiveSplit.tsx
  src/ui/SideBarContent.tsx
Labels: UI, enhancement
