Repository LiveSplit/LiveSplitOne, pull requests merged in 2020-02, with the labels that each got.

#237 Allow the layout to be resized horizontally
  package-lock.json
  package.json
  src/css/Layout.scss
  src/css/LiveSplit.scss
  src/css/SideBarContent.scss
  src/layout/AutoRefreshLayout.tsx
  src/layout/Component.tsx
  src/layout/DetailedTimer.tsx
  src/layout/DragAutoRefreshLayout.tsx
  src/layout/Graph.tsx
  src/layout/Layout.tsx
  src/layout/Timer.tsx
  src/ui/LayoutEditor.tsx
  src/ui/LiveSplit.tsx
  tslint.json
Labels: UI, enhancement

#242 Update Splits and KeyValue components to use flexbox instead of tables
  src/css/KeyValue.scss
  src/css/Splits.scss
  src/layout/KeyValueGeneric.tsx
  src/layout/Split.tsx
  src/layout/SplitLabels.tsx
  src/layout/Splits.tsx
  src/ui/LiveSplit.tsx
Labels: UI, enhancement

#244 Add an option to the Splits to show two rows
  src/css/Splits.scss
  src/layout/Split.tsx
  src/layout/SplitLabels.tsx
Labels: UI, enhancement

#250 Fix styling in Splits and Title
  src/css/DetailedTimer.scss
  src/css/KeyValue.scss
  src/css/Splits.scss
  src/css/Timer.scss
  src/css/Title.scss
  src/css/variables.scss
  src/layout/Split.tsx
  src/layout/Title.tsx
Labels: UI

#252 Adjust styling for mobile and OBS browser source
  src/css/LiveSplit.scss
  src/css/browser_source.scss
  src/css/main.scss
  src/css/mobile.scss
  src/css/variables.scss
  src/layout/AutoRefreshLayout.tsx
  src/layout/Layout.tsx
  src/ui/LiveSplit.tsx
Labels: UI, enhancement

#258 Fix drop region positioning on mobile
  src/css/mobile.scss
Labels: UI, enhancement

#260 Implement a Service Worker
  package-lock.json
  package.json
  src/ui/LiveSplit.tsx
  webpack.config.js
Labels: Android, Google Chrome, enhancement, iOS, performance

#253 Change styling to mostly match the native renderer
  src/css/DetailedTimer.scss
  src/css/KeyValue.scss
  src/css/Layout.scss
  src/css/Separator.scss
  src/css/Splits.scss
  src/css/Timer.scss
  src/css/Title.scss
  src/css/variables.scss
  src/layout/DetailedTimer.tsx
  src/layout/Timer.tsx
  src/type-definitions/scss.d.ts
Labels: UI, enhancement

#255 Implement visual regression testing
  .github/workflows/ci.yml
  .gitignore
  package-lock.json
  package.json
  src/css/Timer.scss
  src/layout/DetailedTimer.tsx
  src/layout/Timer.tsx
  test/layouts/all_components.ls1l
  test/layouts/default.ls1l
  test/layouts/splits_two_rows.ls1l
  test/layouts/splits_with_labels.ls1l
  test/layouts/title_centered_no_game_icon.ls1l
  test/layouts/title_centered_with_game_icon.ls1l
  test/layouts/title_left_no_attempt_count.ls1l
  test/rendering-test.js
  test/splits/celeste.lss
  test/splits/default.lss
  test/splits/pmw3.lss
Labels: CI, UI

#266 Remove the Roboto font
  src/css/Table.scss
  src/css/Time.scss
  src/css/main.scss
  test/rendering-test.js
Labels: UI, enhancement

#267 Fix issues with the Chrome Dev Tools Audit
  src/css/font-awesome.css
  src/css/main.scss
  src/index.html
  src/ui/LayoutEditor.tsx
  src/ui/LiveSplit.tsx
  src/ui/SideBarContent.tsx
Labels: UI, enhancement

#169 Prefer requestAnimationFrame over setInterval
  src/layout/AutoRefreshLayout.tsx
  src/layout/DragAutoRefreshLayout.tsx
  src/ui/SideBarContent.tsx
  src/util/AutoRefresh.tsx
Labels: UI, enhancement, performance

#271 Fix size of game icon to match the two row split icon size
  src/css/Title.scss
  test/rendering-test.js
Labels: UI, enhancement

#269 Improve UI consistency and mobile layout
  src/css/ContextMenu.scss
  src/css/DragUpload.scss
  src/css/HotkeyButton.scss
  src/css/LayoutEditor.scss
  src/css/LiveSplit.scss
  src/css/RunEditor.scss
  src/css/SettingsEditor.scss
  src/css/SideBarContent.scss
  src/css/Table.scss
  src/css/main.scss
  src/css/mobile.scss
  src/css/variables.scss
  src/ui/LayoutEditor.tsx
  src/ui/LiveSplit.tsx
  src/ui/RunEditor.tsx
  src/ui/Settings.tsx
Labels: Android, UI, enhancement, iOS

#274 Create an About dialog
  package-lock.json
  package.json
  src/css/About.scss
  src/type-definitions/webpack-globals.d.ts
  src/ui/About.tsx
  src/ui/LiveSplit.tsx
  src/ui/SideBarContent.tsx
  webpack.config.js
Labels: UI, enhancement
