Repository LiveSplit/LiveSplitOne, pull requests merged in 2024-06, with the labels that each got.

#907 Clone the entire history in the CI workflow
  .github/workflows/ci.yml
  webpack.config.js
Labels: bug, enhancement, CI, high priority

#908 Fix Date matching for Changelog generation
  webpack.config.js
Labels: bug, enhancement, CI, high priority

#909 Remove the remaining Electron code
  package.json
  src/electronMain.js
Labels: enhancement

#910 Implement Save On Reset
  src/storage/index.tsx
  src/ui/LSOEventSink.ts
  src/ui/LiveSplit.tsx
  src/ui/SettingsEditor.tsx
  src/ui/SplitsSelection.tsx
  src/util/AutoRefresh.tsx
  webpack.config.js
Labels: enhancement

#912 Add indicators for unsaved changes
  src/css/Sidebar.scss
  src/ui/LSOEventSink.ts
  src/ui/LayoutView.tsx
  src/ui/LiveSplit.tsx
  src/ui/SplitsSelection.tsx
  src/ui/TimerView.tsx
Labels: enhancement, UI

#914 Save the layout dimensions when saving layout
  src/storage/index.tsx
  src/ui/LayoutEditor.tsx
  src/ui/LayoutView.tsx
  src/ui/LiveSplit.tsx
  src/ui/TimerView.tsx
Labels: enhancement

#915 Fix some small bugs
  src/index.tsx
  src/ui/LSOEventSink.ts
  src/ui/LiveSplit.tsx
  src/util/FrameRate.ts
Labels: bug, enhancement, Chromium

#921 Fix the margin for the PWA Icon on iOS
  webpack.config.js
Labels: enhancement, iOS

#922 Use background for Android icon
  webpack.config.js
Labels: enhancement, Android

#923 Store the comparison and timing method
  src/index.tsx
  src/storage/index.tsx
  src/ui/LiveSplit.tsx
  webpack.config.js
Labels: enhancement

#924 Enable the WebAssembly Multivalue feature
  buildCore.js
Labels: enhancement, performance

#925 Make the PWA Icon maskable
  src/assets/maskable.svg
  webpack.config.js
Labels: enhancement

#930 Clean up some async race conditions & CSS fixes
  src/css/Dialog.scss
  src/css/HotkeyButton.scss
  src/css/LiveSplitServerButton.scss
  src/css/RunEditor.scss
  src/css/Sidebar.scss
  src/css/Table.scss
  src/css/Toggle.scss
  src/css/main.scss
  src/ui/Dialog.tsx
  src/ui/LSOEventSink.ts
  src/ui/LiveSplit.tsx
  src/ui/RunEditor.tsx
  src/ui/Settings.tsx
  src/ui/SplitsSelection.tsx
  src/util/FileUtil.ts
  src/util/SplitsIO.ts
Labels: bug, enhancement, iOS, UI, high priority

#931 Request only a single JS bundle from `index.ts`
  src/index.tsx
  src/indexDelayed.ts
Labels: performance
